### ISSUE TITLE
Relative imports problem

### ISSUE THREAD

**Issue by mpodgorny** [nokia-wroclaw/innovativeproject-sudoku#20]
https://github.com/nokia-wroclaw/innovativeproject-sudoku/blob/13bd47ddfcfe570807b9b274f5e98047d8e30f02/backend/src/main.py#L3

Launching with uvicorn gives message: "attempted relative import with no known parent package". Looking for work-arounds.

**Comment by wadamek65** [comment]
depending on where the routers lies try simply: `from routers import login` without the relative dot.
