### ISSUE TITLE
[pylint] No name 'BaseModel' in module 'pydantic' 

### ISSUE THREAD

**Issue by mpodgorny** [nokia-wroclaw/innovativeproject-sudoku#39]
![Screenshot from 2019-12-03 01-05-56](https://user-images.githubusercontent.com/39701478/70005236-21bceb80-1569-11ea-9341-762888b27d68.png)
Error occurs despite the fact that pydantic is installed in Pipfile and Pipfile.lock is up to date. I'll use ugly hack `# pylint: disable=E0611` till I repair that.

**Comment by sns** [comment]
I have the same issue. Is this fixed?

**Comment by rootUJ99** [comment]
@sns  Nope same issue occurred to me

**Comment by bilunsun** [comment]
same here

**Comment by Kludex** [comment]
Should we create another issue or reopen this one?

**Comment by tekumara** [comment]
Alternate workaround: add `extension-pkg-whitelist=pydantic` to *.pylintrc*

See duplicate issue https://github.com/samuelcolvin/pydantic/issues/1219

**Comment by spolloni** [comment]
@mpodgorny can we reopen this?
